# Generated by Django 5.0.4 on 2024-05-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taklif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('Date', models.DateTimeField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
